### ISSUE TITLE
Нет ссылки на адресе сайта, ведущего с  pages на io

### ISSUE THREAD

**Issue by xfiendx4life** [OvsYAnkaII/Floppa_Site#1]

**Comment by stufade** [comment]
Извините, не совсем понял в чем проблема, ссылка работает нормально

**Comment by xfiendx4life** [comment]
Да, но я должен на нее нажать и перейти, а не вставлять в строку ввода

пт, 10 сент. 2021 г., 19:58 stufade ***@***.***>:

**Comment by stufade** [comment]
Если я Вас правильно понимаю, то вы про сайт ovsyankaii.github.io. Но это не тот, что для дз. Мы сразу сделали название этого репозитория и скинули его в форму, а потом я уже понял что можно было бы выложить его на github pages. Но он не работает на других репозиториях, если нет ovsyankaii.github.io, поэтому мы его создали, чтобы работал branch "gh-pages" на этом репозитории. 

Ссылка на наш сайт - https://ovsyankaii.github.io/Floppa_Site/Main.html и она находится в readme этого репозитория

**Comment by xfiendx4life** [comment]
Ок. Неважно.
Возможно я неправ, возможно на уроке разберемся, когда будет визуально
видно.

пт, 10 сент. 2021 г., 20:49 stufade ***@***.***>:
