### ISSUE TITLE
Меню на каждой странице

### ISSUE THREAD

**Issue by xfiendx4life** [OvsYAnkaII/Floppa_Site#2]

**Comment by OvsYAnkaII** [comment]
добавил на все страницы ссылки на все страницы, принимайте работу. Этот Issue report можно закрыть?

**Comment by xfiendx4life** [comment]
Я потом посмотрю, если сделано, то конечно можно.

пт, 10 сент. 2021 г., 22:29 OvsYAnkaII ***@***.***>:

**Comment by xfiendx4life** [comment]
Меню наверх на всех страницах

**Comment by OvsYAnkaII** [comment]
done
